### ISSUE TITLE
This entry failed to be executed

### ISSUE THREAD

**Issue by 18230** [BandaySajid/chatgpt-node#7]
const { authenticated, accessToken, error } = verifySession(this.#email);

return false undefined undefined

**Comment by 18230** [comment]
E:\chatgpt-node\src\utils\verify_session.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at verifySession (file:///E:/chatgpt-node/src/utils/verify_session.js:18:25)
    at Gpt.authenticate (file:///E:/chatgpt-node/src/lib/Gpt.js:37:59)
    at file:///E:/chatgpt-node/index.js:11:42
    at file:///E:/chatgpt-node/index.js:20:3
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  code: 'MODULE_NOT_FOUND',

**Comment by BandaySajid** [comment]
I have Updated the code and its working fine on Linux, the problem is with windows, there are some issues with authentication, so need to fix that

**Comment by BandaySajid** [comment]
> const { authenticated, accessToken, error } = verifySession(this.#email);
> 
> return false undefined undefined

All the issues are fixed now

**Comment by BandaySajid** [comment]
Download the latest version, 1.0.10

**Comment by 18230** [comment]
ok
